require('./tool/jqFP.js');
require('./tool/jqUI.js');
let Manage = require('./container/PageComponent.js');
let data = [
	 ['js',0.3,"red"],
	 ['h5',0.2,'black'],
     ['css3',0.1,'yellow'],
	 ['jq',0.3,'deeppink'],
	 ['rt',0.1,'#336688']
]
Manage
     .init()
     	.addPage('onePage')
     		.addComponent({
     			type:"base",
     			width:428,
     			height:92,
     			center:true,
     			css:{
     				top:0,
     				opacity:0,
     				backgroundImage:"url('./src/img/logoIndex.png')"
     			},
     			animateIn:{
     				top:120,
     				opacity:1,
     			},
     			animateOut:{
     				top:0,
     				opacity:0,
     			}
     		})
     		.addComponent({
     			type:"base",
     			name:'shake',
     			width:370,
     			height:96,
     			center:true,
     			css:{
     				top:200,
     				left:-50,
     				opacity:0,
     				backgroundImage:"url('./src/img/slogan.png')"
     			},
     			animateIn:{
     				left:'50%',
     				opacity:1,
     			},
     			animateOut:{
     				left:-50,
     				opacity:0,
     			},
     			delay:500
     		})
     		.addComponent({
     			type:"base",
     			width:346,
     			height:494,
     			css:{
     				position:'absolute',
     			    bottom:-20,
     				left:-20,
     				opacity:0,
     				backgroundImage:"url('./src/img/left.png')"
     			},
     			animateIn:{
     				bottom:0,
     				left:20,
     				opacity:1,
     			},
     			animateOut:{
     				left:-20,
     				opacity:0,
     			},
     			delay:1000
     		})
     		.addComponent({
     			type:"base",
     			width:324,
     			height:450,
     			css:{
     				position:'absolute',
     				bottom:-20,
     				right:-20,
     				opacity:0,
     				backgroundImage:"url('./src/img/right.png')"
     			},
     			animateIn:{
     				bottom:0,
     				right:20,
     				opacity:1,
     			},
     			animateOut:{
     				bottom:-20,
     				right:-20,
     				opacity:0,
     			},
     			delay:1500
     		})

/*-------------------------------------------------------------------*/


     	.addPage("twoPage") 
     	 	.addComponent({
     			type:"base",
     			width:500,
     			height:124,
     			css:{
     				position:'absolute',
     				top:-20,
     				opacity:0,
     				backgroundImage:"url('./src/img/mind.png')"
     			},
     			animateIn:{
     				top:80,
     				left:0,
     				opacity:1,
     			},
     			animateOut:{
     				top:-20,
     				opacity:0,
     			},
     			delay:500
     		})


     		.addComponent({
     			type:"base",
     			width:500,
     			height:50,
     			center:true,
     			text:'用实力让情怀落地!',
     			css:{
     				position:'absolute',
     			     top:0,
     				opacity:0,
     	               lineHeight:'50px',
     	               textAlign:'center',
     	               color:'orange',
     	               fontSize:25,
     	               fontWeight:'bold'
     			},
     			animateIn:{
     				top:160,
     				opacity:1,
     			},
     			animateOut:{
     				top:-20,
     				opacity:0,
     			},
     			delay:1000
     		})


     		.addComponent({
     			type:"base",
     			width:522,
     			height:336,
     			center:true,
                    text:'渡一教育成立于2015年，在邓哥，成哥，思彤哥的带领下已经向着高端编程教育公迈进，渡一Deram Factory,渡一web coffee,于今年成立',
     			css:{
     				position:'absolute',
     			     bottom:150,
     				opacity:0,
     				backgroundImage:"url('./src/img/dialog.png')",
                         textAlign:'justfiy',
                         fontWeight:900,
                         fontSize:18,
     			},
     			animateIn:{
     				bottom:200,
     				opacity:1,
     			},
     			animateOut:{
     				bottom:150,
     				opacity:0,
     			},
     			delay:1500
     		})

               .addComponent({
                    type:"base",
                    width:516,
                    height:306,
                    center:true,
                    css:{
                         position:'absolute',
                         bottom:-20,
                         opacity:0,
                         backgroundImage:"url('./src/img/people.png')"
                    },
                    animateIn:{
                         bottom:20,
                         opacity:1,
                    },
                    animateOut:{
                         bottom:-20,
                         opacity:0,
                    },
                    delay:2000
               })
/*-------------------------------------------------------------------*/

     	.addPage('threePage')
               .addComponent({
                    type:"base",
                    width:500,
                    height:124,
                    css:{
                         position:'absolute',
                         top:-20,
                         opacity:0,
                         backgroundImage:"url('./src/img/bar.png')"
                    },
                    animateIn:{
                         top:80,
                         left:0,
                         opacity:1,
                    },
                    animateOut:{
                         top:-20,
                         opacity:0,
                    },
                    delay:500
               })
               .addComponent({
                    type:"base",
                    width:500,
                    height:50,
                    center:true,
                    text:'课程体系柱状图',
                    css:{
                         position:'absolute',
                         top:0,
                         opacity:0,
                         lineHeight:'50px',
                         textAlign:'center',
                         color:'orange',
                         fontSize:25,
                         fontWeight:'bold'
                    },
                    animateIn:{
                         top:200,
                         opacity:1,
                    },
                    animateOut:{
                         top:-20,
                         opacity:0,
                    },
                    delay:1000
               })
               .addComponent({
                    type:"bar",
                    width:500,
                    height:500,
                    center:true,
                    css:{
                         position:'absolute',
                         bottom:-20,
                         opacity:0,
                    },
                    animateIn:{
                         bottom:20,
                         opacity:1,
                    },
                    animateOut:{
                         bottom:-20,
                         opacity:0,
                    },
                    delay:1500,
                    data:data
               })
     /*----------------------------------------------------------------*/
     	.addPage('fourPage')
               .addComponent({
                    type:"base",
                    width:500,
                    height:124,
                    css:{
                         position:'absolute',
                         top:-20,
                         opacity:0,
                         backgroundImage:"url('./src/img/polyline.png')"
                    },
                    animateIn:{
                         top:80,
                         left:0,
                         opacity:1,
                    },
                    animateOut:{
                         top:-20,
                         opacity:0,
                    },
                    delay:500
               })
               .addComponent({
                    type:"base",
                    width:500,
                    height:50,
                    center:true,
                    text:'课程难度级别分布',
                    css:{
                         position:'absolute',
                         top:0,
                         opacity:0,
                         lineHeight:'50px',
                         textAlign:'center',
                         color:'red',
                         fontSize:25,
                         fontWeight:'bold'
                    },
                    animateIn:{
                         top:200,
                         opacity:1,
                    },
                    animateOut:{
                         top:-20,
                         opacity:0,
                    },
                    delay:1000
               })
               .addComponent({
                    type:"poly",
                    width:500,
                    height:500,
                    center:true,
                    css:{
                         position:'absolute',
                         bottom:-20,
                         opacity:0,
                    },
                    animateIn:{
                         bottom:40,
                         opacity:1,
                    },
                    animateOut:{
                         bottom:-20,
                         opacity:0,
                    },
                    delay:1500,
                    data:data
               })
     	.addPage('fivePage')
               .addComponent({
                    type:"base",
                    width:500,
                    height:124,
                    css:{
                         position:'absolute',
                         top:-20,
                         opacity:0,
                         backgroundImage:"url('./src/img/pie.png')"
                    },
                    animateIn:{
                         top:80,
                         left:0,
                         opacity:1,
                    },
                    animateOut:{
                         top:-20,
                         opacity:0,
                    },
                    delay:500
               })
               .addComponent({
                    type:"base",
                    width:500,
                    height:50,
                    center:true,
                    text:'课程方向分布',
                    css:{
                         position:'absolute',
                         top:0,
                         opacity:0,
                         lineHeight:'50px',
                         textAlign:'center',
                         color:'red',
                         fontSize:25,
                         fontWeight:'bold'
                    },
                    animateIn:{
                         top:200,
                         opacity:1,
                    },
                    animateOut:{
                         top:-20,
                         opacity:0,
                    },
                    delay:1000
               })
               .addComponent({
                    type:"pie",
                    width:500,
                    height:500,
                    center:true,
                    css:{
                         position:'absolute',
                         bottom:-20,
                         opacity:0,
                    },
                    animateIn:{
                         bottom:40,
                         opacity:1,
                    },
                    animateOut:{
                         bottom:-20,
                         opacity:0,
                    },
                    delay:1500,
                    data:data
               })
     	.addPage('sixPage')
               .addComponent({
                    width:48,
                    height:26,
                    center:true,
                    name:'up',
                    css:{
                         position:'absolute',
                         top:-20,
                         opacity:0,
                         backgroundImage:"url('./src/img/back.png')"
                    },
                    animateIn:{
                         top:120,
                         opacity:1,
                    },
                    animateOut:{
                         top:-20,
                         opacity:0,
                    },
                    delay:500,
                    eventType:{
                         click:() => {
                              Manage.Container.fullpage.moveTo(1);
                         }
                    }
               })
               .addComponent({
                    width:428,
                    height:92,
                    name:'shake',
                    center:true,
                    css:{
                         position:'absolute',
                         right:-20,
                         opacity:0,
                         backgroundImage:"url('./src/img/logo.png')"
                    },
                    animateIn:{
                         top:200,
                         right:50,
                         opacity:1,
                    },
                    animateOut:{
                         right:-20,
                         opacity:0,
                    },
                    delay:1000,
               })

     		.addComponent({
                    type:"base",
                    width:370,
                    height:96,
                    center:true,
                    css:{
                         bottom:-20,
                         opacity:0,
                         backgroundImage:"url('./src/img/slogan.png')"
                    },
                    animateIn:{
                         bottom:200,
                         opacity:1,
                    },
                    animateOut:{
                         bottom:-20,
                         opacity:0,
                    },
                    delay:1500
               })
               .addComponent({
                    type:"base",
                    width:128,
                    height:120,
                    css:{
                         position:'absolute',
                         top:100,
                         right:100,
                         opacity:0,
                         backgroundImage:"url('./src/img/share.png')"
                    },
                    animateIn:{
                         top:0,
                         right:0,
                         opacity:1,
                    },
                    animateOut:{
                         top:100,
                         right:100,
                         opacity:0,
                    },
                    delay:500
               })
     		.load();





